##
## Postgres setup - To use local docker instance see src/test/main/StartPostgresDocker.main()
##
ebean:
  dbSchema: ebean_monitor
  migration:
    run: true

db:
  user: ebean_monitor
  password: test
  url: jdbc:postgresql://localhost:7432/ebean_monitor

datasource:
  db:
    username: ${db.user:ebean_monitor}
    password: ${db.password:test}
#    url: ${db.url:jdbc:postgresql://localhost:7432/ebean_monitor}
    url: jdbc:postgresql://localhost:7432/ebean_monitor
    driver: ${db.driver:org.postgresql.Driver}


## H2 setup - In memory
#datasource:
#  db:
#    username: sa
#    password: sa
#    url: jdbc:h2:mem:myapp
#    driver: org.h2.Driver
#
#ebean:
#  ddl:
#    generate: true
#    run: true
